PROnline/Models/Assessments/AssessmentResult.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PROnline.Models.Users;
using System.ComponentModel.DataAnnotations;

namespace PROnline.Models.Assessments
{
    //测评结果
    public class AssessmentResult
    {
        public Guid AssessmentResultID { get; set; }

        //接受测评的学生
        public Guid StudentID { get; set; }

        public virtual Student Student { get; set; }

        //结论
        [MaxLength(100)]
        [Display(Name = "结论")]
        public String Conclusion { get; set; }

        //建议
        [MaxLength(100)]
        [Display(Name = "建议")]
        public String Advice { get; set; }

        public virtual IList<AssessmentResultOption> ResultOptionList { get; set; }

        //下一步措施：继续治疗、治愈、转院
        [MaxLength(100)]
        [Display(Name = "下一步措施")]
        public String Action { get; set; }

        public DateTime CreateDate { get; set; }
    }
}

PROnline/Controllers/Assessment/AssessmentResultController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PROnline.Models.Assessments;
using PROnline.Models;
using PROnline.Models.Users;
using PROnline.Controllers.Users;

namespace PROnline.Controllers.Assessment
{ 
    public class AssessmentResultController : Controller
    {
        private PROnlineContext db = new PROnlineContext();

        //
        // GET: /AssessmentResult/
        //参数：Student=>StudentID
        [ValidateInput(false)]
        public ViewResult Index(Guid StudentID)
        {
            List<AssessmentResult> resultList = db.AssessmentResult.Where(a => a.StudentID == StudentID).ToList();
            return View(resultList);
        }

        public ViewResult SchoolNavigation()
        {
            SchoolController sc = new SchoolController();
            ViewBag.SchoolDropDownList = sc.SchoolDropDownList();
            string dd = Request.Params.Get("type");
            ViewBag.type = Request.Params.Get("type");
            String id = Request.Params.Get("SchoolID");
            School school = null;
            if (id != null)
            {
                school = db.School.Find(Guid.Parse(id));
            }
            return View(school);
        }

        //
        // GET: /AssessmentResult/Details/5

        public ViewResult Details(Guid StudentID)
        {
            List<AssessmentResult> result = db.AssessmentResult.Where(a => a.StudentID == StudentID).OrderByDescending(a=>a.CreateDate).ToList();
            ViewBag.schoolID = Request.Params.Get("SchoolID");
            return View(result);
        }

        // GET: /AssessmentQuestion/Assess

        public ActionResult Assess(AssessmentQuestion q)
        {
            String dd = Request.Params.Get("optioncount");          
            return RedirectToAction("Index");
        }

        //
        // GET: /AssessmentResult/Create

        public ActionResult Create()
        {
            AssessmentQuestionController controller = new AssessmentQuestionController();
            ViewBag.list = controller.AllQuestion();
            //便于返回学校
            ViewBag.schoolID = Request.Params.Get("SchoolID");
            return View();
        }

        //
        // POST: /AssessmentResult/Create

        [HttpPost]
        public ActionResult Create(AssessmentResult assessmentresult)
        {
            if (ModelState.IsValid)
            {
                assessmentresult.AssessmentResultID = Guid.NewGuid();
                Guid studentId = Guid.Parse(Request.Params.Get("studentId"));
                assessmentresult.StudentID = studentId;
                if (assessmentresult.ResultOptionList != null)
                {
                    foreach (AssessmentResultOption resultOption in assessmentresult.ResultOptionList)
                    {
                        resultOption.AssessmentResultOptionID = Guid.NewGuid();
                    }
                }
                assessmentresult.CreateDate = DateTime.Now;
                db.AssessmentResult.Add(assessmentresult);
                db.SaveChanges();

                String schoolID = Request.Params.Get("SchoolID");
                return RedirectToAction("SchoolNavigation", new { SchoolID = schoolID, type = "psychological" });  
            }

            return View(assessmentresult);
        }
        
        //
        // GET: /AssessmentResult/Edit/5
 
        public ActionResult Edit(Guid id)
        {
            AssessmentResult assessmentresult = db.AssessmentResult.Find(id);            
            return View(assessmentresult);
        }

        //
        // POST: /AssessmentResult/Edit/5

        [HttpPost]
        public ActionResult Edit(AssessmentResult assessmentresult)
        {
            if (ModelState.IsValid)
            {
                db.Entry(assessmentresult).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(assessmentresult);
        }

        //
        // GET: /AssessmentResult/Delete/5
 
        public ActionResult Delete(Guid id)
        {
            AssessmentResult assessmentresult = db.AssessmentResult.Find(id);
            return View(assessmentresult);
        }

        //
        // POST: /AssessmentResult/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(Guid id)
        {            
            AssessmentResult assessmentresult = db.AssessmentResult.Find(id);
            db.AssessmentResult.Remove(assessmentresult);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

PROnline/Views/AssessmentResult/Create.cshtml
@model PROnline.Models.Assessments.AssessmentResult
@using PROnline.Models.Assessments;
@{
    ViewBag.Title = "新建心理健康状况评估";
    Layout = "~/Views/Shared/Manage/_Edit.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        
<table id="datatable">
<thead>
            <tr>
                <th>
                    题目
                </th>

                <th>
                    无
                </th>

                <th>
                    偶尔
                </th>

                <th>
                    时有
                </th>

                <th>
                    经常
                </th>

                <th>
                    总是
                </th>
                <th></th>
           </tr>
           </thead>
<tbody>
      @{int i = 0; string prefx = "ResultOptionList[";}
      @foreach (var item in ViewBag.list as List<AssessmentQuestion>)
      {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>

        @foreach (AssessmentOption option in item.AssessmentOptionList)
        {
         <td>
           @Html.RadioButton(prefx + i + "].AssessmentOptionID", option.AssessmentOptionID)
           @Html.DisplayFor(modelItem => option.OptionValue)
        </td>
        }
    
        @{i++;}
   </tr>
      }
       @Html.Hidden("optioncount", i)
</tbody>
</table>
@Tools.table("datatable")


        <div class="editor-label">
            @Html.LabelFor(model => model.Conclusion)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Conclusion)
            @Html.ValidationMessageFor(model => model.Conclusion)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Advice)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Advice)
            @Html.ValidationMessageFor(model => model.Advice)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Action)
        </div>
         <div class="editor-field">
            @Html.DropDownList("Action", new SelectList(new List<String> { "继续治疗", "治愈", "转院" }))
        </div>

        <p>
            <input type="submit" value="新建" />
        </p>

        <p class="btn">
            @Html.ActionLink("返回", "SchoolNavigation", new { SchoolID = ViewBag.schoolID, type = "psychological" }, null)
        </p>
    </fieldset>
}

PROnline/Views/AssessmentResult/Delete.cshtml
@model PROnline.Models.Assessments.AssessmentResult

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Manage/_Detail.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>AssessmentResult</legend>

    <div class="display-label">Conclusion</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Conclusion)
    </div>

    <div class="display-label">Advice</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Advice)
    </div>

    <div class="display-label">Action</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Action)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

PROnline/Views/AssessmentResult/Details.cshtml
@model IEnumerable<PROnline.Models.Assessments.AssessmentResult>

@{
    ViewBag.Title = "心理健康状况评估记录";
    Layout = "~/Views/Shared/Manage/_List.cshtml";
}

<table id="datatable">
<thead>
    <tr>
        <th>
            姓名
        </th>
        <th>
            结论
        </th>
        <th>
            建议
        </th>
        <th>
            下一步行动
        </th>
        <th>
            录入日期
        </th>
    </tr>
</thead>
<tbody>
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Student.User.RealName, "Details", new { id = item.AssessmentResultID }, new { target="_blank"})
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Conclusion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Advice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Action)
        </td>
        <td>
           @Html.ActionLink(item.CreateDate.ToString(), "Index", "AssessmentResultOption", new { AssessmentResultID = item.AssessmentResultID }, new { target = "_blank" })
        </td>
    </tr>
}

</tbody>
</table>
@Tools.table("datatable")

<p class="btn">
    @Html.ActionLink("返回", "SchoolNavigation", new { SchoolID = ViewBag.schoolID, type = "psychological" })
</p>

PROnline/Views/AssessmentResult/Edit.cshtml
@model PROnline.Models.Assessments.AssessmentResult

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Manage/_Edit.cshtml";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>AssessmentResult</legend>

        @Html.HiddenFor(model => model.AssessmentResultID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Conclusion)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Conclusion)
            @Html.ValidationMessageFor(model => model.Conclusion)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Advice)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Advice)
            @Html.ValidationMessageFor(model => model.Advice)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Action)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Action)
            @Html.ValidationMessageFor(model => model.Action)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PROnline/Views/AssessmentResult/SchoolNavigation.cshtml
@model PROnline.Models.Users.School
@using PROnline.Models.Users;

@{
    ViewBag.Title = "学校列表";
    Layout = "~/Views/Shared/Manage/_List.cshtml";
}

<!--传回学校ID-->
@using (Html.BeginForm("SchoolNavigation", "AssessmentResult" , FormMethod.Get))
{
    @Html.ValidationSummary(true)

        <input type="hidden" name="type" value=@ViewBag.type />
    
        <div class="editor-label">
            @Html.LabelFor(model => model.SchoolName)
        </div>
        <div class="editor-field">
            @Html.DropDownList("SchoolID", ViewBag.SchoolDropDownList as SelectList)
            <input type="submit" value="选择学校" />
        </div>
    }

 <table id="datatable" >
  <thead>
    <tr>
        <th>
            班主任
        </th>
        <th>
            学生
        </th>
        <th>
            录入
        </th>
        <th>
            查询
        </th>
    </tr>
     </thead>
    <tbody>
    <!--列出学校、班主任、学生-->
@if (Model != null)
{
    foreach (var item in Model.TeacherList as List<Teacher>)
    {
        foreach (var student in item.StudentList as List<Student>)
        {
            if (student.User.isDeleted == false)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.User.RealName)
                </td>
                <td>
                 @Html.ActionLink(student.User.RealName, "Details", "Student", new { id = student.StudentID }, new { target = "_blank" }) 
                </td>
                <td>
               @if (ViewBag.type == "psychological"){
                    @Html.ActionLink("录入心理测评", "Create", "AssessmentResult", new { studentId = student.StudentID, SchoolID = student.Teacher.SchoolID }, null) 
                }else if (ViewBag.type == "study"){
                    @Html.ActionLink("录入学业测评", "Create", "StudyAssessment", new { studentId = student.StudentID, SchoolID = student.Teacher.SchoolID }, null) 
                }
                </td>
                <td>
                @if (ViewBag.type == "psychological"){
                    @Html.ActionLink("心理测评历史记录", "Details", "AssessmentResult", new { StudentID = student.StudentID, SchoolID = student.Teacher.SchoolID }, null)
                }else if (ViewBag.type == "study"){                
                    @Html.ActionLink("学业测评历史记录", "Details", "StudyAssessment", new { StudentID = student.StudentID, SchoolID = student.Teacher.SchoolID }, null) 
                }
                </td>
            </tr>
            }
        }
    }
}
</tbody>
</table>
@Tools.table("datatable")
