PROnline/Models/Guides/AboutUs.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace PROnline.Models.Guides
{
    public class AboutUs
    {
        public Guid ID { get; set; }
        [Display(Name="标题"),Required]
        public String Title { get; set; }
        
        public DateTime CreateDate { get; set; }
        [Display(Name="显示序号")]
        public int Index { get; set; }
        [Display(Name = "内容")]
        public String Content { get; set; }
        [Display(Name="是否公开")]
        public bool IsPublic { get; set; }
    }
}
 

PROnline/Controllers/Guides/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PROnline.Models;
using PROnline.Models.Guides;
using PROnline.Src;
using System.Data;

namespace PROnline.Controllers.Guides
{
    public class AboutUsController : Controller
    {
        //
        // GET: /AboutUs/

        PROnlineContext db = new PROnlineContext();

        public ActionResult Index()
        {
            var list = db.AboutUs.ToList();
            return View(list);
        }

        //
        // GET: /AboutUs/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Top()
        {
            var result = db.AboutUs.OrderBy(r => r.CreateDate).ToList();
            return View(result);
        }

        //
        // GET: /AboutUs/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /AboutUs/Create

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(AboutUs au)
        {
            try
            {
                au.ID = Guid.NewGuid();
                au.CreateDate = DateTime.Now;
                db.AboutUs.Add(au);
         
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        //
        // GET: /AboutUs/Edit/5
 
        public ActionResult Edit(Guid id)
        {
            var result = db.AboutUs.Find(id);
            return View(result);
        }

        //
        // POST: /AboutUs/Edit/5

        [HttpPost]
        public ActionResult Edit(AboutUs au)
        {
            db.Entry(au).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //
        // GET: /AboutUs/Delete/5
 
        public ActionResult Delete(int id)
        {
            var result = db.AboutUs.Find(id);
            return View(result);
        }

        //
        // POST: /AboutUs/Delete/5

        [HttpPost]
        public ActionResult Delete(Guid id)
        {
            var result = db.AboutUs.Find(id);
            db.AboutUs.Remove(result);
            return RedirectToAction("Index");
        }

        public ActionResult Show(Guid id)
        {
            ViewBag.list = db.AboutUs.ToList();
            var result = db.AboutUs.Find(id);
            return View(result);
        }

    }
}

PROnline/Views/AboutUs/Create.cshtml
@model PROnline.Models.Guides.AboutUs

@{
    ViewBag.Title = "创建[关于我们]";
    Layout = "~/Views/Shared/Manage/_Edit.cshtml";
}

@section Head{
<script src="@Url.Content("~/Content/ckeditor/ckeditor.js")" type="text/javascript"></script>

}
@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field p100">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Content)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Content)
            @Html.ValidationMessageFor(model => model.Content)
            @Tools.richbox("Content", "/Resources/EditorSave")
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsPublic)
        </div>
        <div class="editor-field">
            @Html.CheckBoxFor(model => model.IsPublic, new {text="公开" })
            @Html.ValidationMessageFor(model => model.IsPublic)
        </div>

        <p>
            <input type="submit" value="创建" />|@Html.ActionLink("返回", "Index")
        </p>
    </fieldset>
}



PROnline/Views/AboutUs/Index.cshtml
@model IEnumerable<PROnline.Models.Guides.AboutUs>

@{
    ViewBag.Title = "关于我们";
    Layout = "~/Views/Shared/Manage/_List.cshtml";
}


<p class="btn">
    @Html.ActionLink("添加", "Create")
</p>
<table id="tableList">
<thead>
    <tr>
        
        <th>
            标题
        </th>

        <th style="width:130px">#</th>
    </tr>
</thead>
<tbody>
@foreach (var item in Model) {
    <tr>

        <td>
            @item.Title
        </td>
        <td>
            @Html.ActionLink("修改", "Edit", new { id=item.ID }) |
            @Html.ActionLink("详情", "Details", new { id=item.ID }) |
            @Html.ActionLink("删除", "Delete", new { id=item.ID })
        </td>
    </tr>
}
</tbody>
</table>
@Tools.table("tableList")


PROnline/Views/AboutUs/Show.cshtml
@model PROnline.Models.Guides.AboutUs

@{
    ViewBag.Title = "新手导航详情";
    Layout = "~/Views/Shared/Normal/_ContentList.cshtml";
}
<link rel="Stylesheet" type="text/css" href="/Content/app/resource/resource.css" />

<div class="grid_3 typemenu">
<h2>关于我们</h2>
<ul>
@foreach (var ab in @ViewBag.list as List<PROnline.Models.Guides.AboutUs>)
{
   <li><a href="/AboutUs/Show/@ab.ID">@ab.Title</a></li> 
}
</ul>
</div>
<div class="grid_9">
<fieldset>

    <div class="display-label">标题</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">详情</div>
    <div class="display-field">
        @Html.Raw(Model.Content)
    </div>

</fieldset>
</div>

PROnline/Views/AboutUs/Top.cshtml
@model IEnumerable<PROnline.Models.Guides.AboutUs>
@using PROnline.Src;
@{
    ViewBag.Title = "Top";
    Layout = "~/Views/Shared/_Empty.cshtml";
}

<div class="head">
<h3>关于我们 </h3>

</div>
<p>
<ul>
@foreach (var item in Model)
{
    <li>
    <span class="title">&raquo;&nbsp;@Html.ActionLink(Utils.title(item.Title), "Show", "AboutUs", new { id = @item.ID }, null)</span></li>

}
</ul>
</p>
